### ISSUE TITLE
"Array contains both Scalar and Non-Scalar values" error after recent update (2.0.10 > 2.0.12)

### ISSUE THREAD

**Issue by ntbutler-nbcs** [Simbiat/array2table#1]
Hi there.

After a recent update, I am getting **UnexpectedValueException** errors _Array contains both scalar and non-scalar values._ whenever trying to use array2table.

I am using a header array (array of strings) in the setHeader method, and a multidimensional array of string arrays in the generate method. It works fine for me on release 2.0.10, but fails on 2.0.12.

Here is a simple example of blade file that does not work under 2.0.12 but does under 2.0.10:

```blade
  {!!
      (new \Simbiat\array2table)
          ->setSemantic(true)
          ->setSanitize(false)
          ->setEditable(false)
          ->setHeader(["Col1","Col2","Col3"])
          ->generate([
              ["row1Val1", "row1Val2", "row1Val3"],
              ["row2Val1", "row2Val2", "row2Val3"],
              ["row3Val1", "row3Val2", "row3Val3"],
          ])

  !!}
```

I believe the issue might be related to commit 70437d82da409d4a61a3cca22cea3fcf8a6b0208 and the change in moving to ArrayHelpers::isMultiDimensional

Any help would be appreciated :upside_down_face:

**Comment by Simbiat** [comment]
You are correct, this was caused by this. Essentially I lost a branch when I moved `isMulti` outside of the class, and thus it was not behaving correctly. I have updated `ArrayHelpers`, and also updated `composer.json` for `array2tables` to use a more exact minimum version of the helpers. Run composer update and you will be good to go.

I am also surprised someone is actually using this 😅

**Comment by ntbutler-nbcs** [comment]
@Simbiat - perfection, love your work! Generating nice tables is so tedious, so I'm loving the fact you've built this 😄.
